### ISSUE TITLE
Trainer Randomizing Not Working

### ISSUE THREAD

**Issue by MidgeThePidge** [kwsch/pk3DS#87] opened 2017-01-10 23:04 UTC
PK3DS is not randomizing the trainer's pokemon. I know that I'm putting all the files in the correct places so this may be an issue.

**Comment by sora10pls** [comment] 2017-01-11 04:17
are you using latest commit? it's working as intended for me; there is an outdated build that was circulating for a while that didn't save trainer edits unless they were accessed, and that's been fixed as of commit ca0fbb1 from just about 1 month ago

**Comment by MidgeThePidge** [comment] 2017-01-11 19:54
How do I download the latest commit?

**Comment by kwsch** [comment] 2017-01-11 20:03
From the project page you can either clone/download the source code, and compile with msbuild/visual studio.

[Compiled builds are on the same CI server as PKHeX](http://teamcity.skyeditor.org/overview.html), navigate around to the artifacts of a given commit to find the zip.

**Closed by kwsch** 2017-01-11 20:03 UTC
