### ISSUE TITLE
[Feature Request] SMWE Table Copy

### ISSUE THREAD

**Issue by Aussifer** [kwsch/pk3DS#260] opened 2017-12-19 09:55 UTC
Basically, a way to copy SMWE tables within a map location to other maps - e.g. copy the data from "000 - 4 (Day)" to "000 - 7 (Day)" or "000 - 8 (Night)", etc.

Hypothetically, could it function as an "Import Table" option, with a list of options within the same location that you pick, which then overwrites the old table's slots with the Import table's slots? Code design isn't my forte, so I'm not sure how the end result might look, but at a glance it seems like it's something that could be done. As a QoL thing, keeping the import options restricted to within the same location cluster wouldn't be essential if it's too cumbersome to implement.

**Comment by sora10pls** [comment] 2017-12-19 13:44
Duplicate of #182

**Closed** 2017-12-19 17:12 UTC
